import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/web/layout/header";
import { Itim } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const itim = Itim({
  subsets: ['latin'],
  weight: '400',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={itim.className}
      >
        {children}
      </body>
    </html>
  );
}

